spring:
  application:
    name: gateway

server:
  port: 8082

nats:
  spring:
    server: nats://localhost:4222
  timeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: "CHANGE-ME-super-secret-key-very-long-at-least-256-bits"
  expiration-ms: 900000 # 15 minutes
  cookie-name: AUTH_TOKEN

app:
  cookie:
    secure: false
    sameSite: None

logging:
  level:
    com.example.gateway: DEBUG
    io.nats: INFO